version: '3.8'
services:
  db:
    image: postgres:13
    container_name: sql_challenge_ai_db
    environment:
      POSTGRES_DB: sqlchallengeai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: